ABC.exe:main.o big2.o fact.o rev.o pali.o fibo.o sum.o big3.o sort.o
	gcc -o ABC.exe main.o big2.o fact.o rev.o pali.o fibo.o sum.o big3.o sort.o
main.o:main.c
	gcc -c main.c
big2.c:big2.o
	gcc -c big2.c
fact.o:fact.c
	gcc -c fact.c
rev.o:rev.c
	gcc -c rev.c
pali.o:pali.c
	gcc -c pali.c
fibo.o:fibo.c
	gcc -c fibo.c
sum.o:sum.c
	gcc -c sum.c
big3.o:big3.c
	gcc -c big3.c
sort.o:sort.c
	gcc -c sort.c
